----------------------------------------------------------------------------------------------------
--- コンテキスト階層表示（パンくずリスト）
----------------------------------------------------------------------------------------------------
return {
	"utilyre/barbecue.nvim",
	name = "barbecue",
	version = "*",
	dependencies = {
		"SmiteshP/nvim-navic",
		"nvim-tree/nvim-web-devicons",
	},
	event = { "BufReadPre", "BufNewFile" },
	opts = {
		attach_navic = true,
		create_autocmd = true,
		include_buftypes = { "" },
		exclude_filetypes = { "netrw", "toggleterm", "oil" },
		modifiers = {
			dirname = ":~:.",
			basename = "",
		},
		show_dirname = true,
		show_basename = true,
		show_modified = false,
		modified = function(bufnr) return vim.bo[bufnr].modified end,
		show_navic = true,
		lead_custom_section = function() return " " end,
		custom_section = function() return " " end,
		theme = "auto",
		context_follow_icon_color = false,
		symbols = {
			modified = "●",
			ellipsis = "…",
			separator = "",
		},
		kinds = {
			File = "",
			Module = "",
			Namespace = "",
			Package = "",
			Class = "",
			Method = "",
			Property = "",
			Field = "",
			Constructor = "",
			Enum = "練",
			Interface = "",
			Function = "",
			Variable = "",
			Constant = "",
			String = "",
			Number = "",
			Boolean = "◩",
			Array = "",
			Object = "",
			Key = "",
			Null = "ﳠ",
			EnumMember = "",
			Struct = "",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
	},
	keys = {
		{ "<leader>vb", function() require("barbecue.ui").toggle() end, desc = "パンくずリスト切替" },
	},
}